Repository opexdev/core, pull requests merged in 2022-08, with the labels that each got.

#310 Close #292, Add elk stack for monitoring logs
  docker-compose.build.yml
  docker-compose.override.yml
  docker-compose.yml
  docker-images/filebeat/Dockerfile
  docker-images/filebeat/filebeat.yml
Labels: enhancement

#311 docker-compose: Fix filebeat container name
  docker-compose.build.yml
Labels: bug

#314 Close #296, Change candle data order to ASC
  market/market-ports/market-persister-postgres/src/main/kotlin/co/nilin/opex/market/ports/postgres/dao/TradeRepository.kt
Labels: bug

#317 316 registration clean up
  docker-compose.yml
  user-management/keycloak-gateway/src/main/kotlin/co/nilin/opex/auth/gateway/data/ForgotPasswordRequest.kt
  user-management/keycloak-gateway/src/main/kotlin/co/nilin/opex/auth/gateway/extension/UserManagementResource.kt
  user-management/keycloak-gateway/src/main/resources/application.yml
  utility/error-handler/src/main/kotlin/co/nilin/opex/utility/error/data/OpexError.kt
Labels: bug, enhancement

#318 v1.0.0-beta.5
  api/api-core/src/main/kotlin/co/nilin/opex/api/core/inout/Currency.kt
  api/api-core/src/main/kotlin/co/nilin/opex/api/core/inout/CurrencyImplementation.kt
  api/api-core/src/main/kotlin/co/nilin/opex/api/core/spi/BlockchainGatewayProxy.kt
  api/api-core/src/main/kotlin/co/nilin/opex/api/core/spi/MarketUserDataProxy.kt
  api/api-ports/api-binance-rest/src/main/kotlin/co/nilin/opex/api/ports/binance/config/SecurityConfig.kt
  api/api-ports/api-binance-rest/src/main/kotlin/co/nilin/opex/api/ports/binance/controller/AccountController.kt
  api/api-ports/api-binance-rest/src/main/kotlin/co/nilin/opex/api/ports/binance/controller/LandingController.kt
  api/api-ports/api-binance-rest/src/main/kotlin/co/nilin/opex/api/ports/binance/controller/MarketController.kt
  api/api-ports/api-binance-rest/src/main/kotlin/co/nilin/opex/api/ports/binance/controller/WalletController.kt
  api/api-ports/api-binance-rest/src/main/kotlin/co/nilin/opex/api/ports/binance/data/CurrencyNetworkResponse.kt
  api/api-ports/api-proxy-rest/src/main/kotlin/co/nilin/opex/api/ports/proxy/data/AllOrderRequest.kt
  api/api-ports/api-proxy-rest/src/main/kotlin/co/nilin/opex/api/ports/proxy/data/TradeRequest.kt
  api/api-ports/api-proxy-rest/src/main/kotlin/co/nilin/opex/api/ports/proxy/impl/BlockchainGatewayProxyImpl.kt
  api/api-ports/api-proxy-rest/src/main/kotlin/co/nilin/opex/api/ports/proxy/impl/MarketUserDataProxyImpl.kt
  bc-gateway/bc-gateway-app/src/main/kotlin/co/nilin/opex/bcgateway/app/config/SecurityConfig.kt
  bc-gateway/bc-gateway-app/src/main/kotlin/co/nilin/opex/bcgateway/app/controller/CurrencyController.kt
  bc-gateway/bc-gateway-core/src/main/kotlin/co/nilin/opex/bcgateway/core/model/CurrencyImplementation.kt
  bc-gateway/bc-gateway-core/src/main/kotlin/co/nilin/opex/bcgateway/core/spi/CurrencyHandler.kt
  bc-gateway/bc-gateway-core/src/test/kotlin/co/nilin/opex/bcgateway/core/service/AssignAddressServiceImplUnitTest.kt
  bc-gateway/bc-gateway-ports/bc-gateway-persister-postgres/src/main/kotlin/co/nilin/opex/bcgateway/ports/postgres/impl/CurrencyHandlerImpl.kt
  docker-compose.yml
  market/market-app/src/main/kotlin/co/nilin/opex/market/app/controller/UserDataController.kt
  market/market-core/src/main/kotlin/co/nilin/opex/market/core/inout/AllOrderRequest.kt
  market/market-core/src/main/kotlin/co/nilin/opex/market/core/inout/TradeRequest.kt
  market/market-core/src/main/kotlin/co/nilin/opex/market/core/spi/UserQueryHandler.kt
  market/market-ports/market-persister-postgres/src/main/kotlin/co/nilin/opex/market/ports/postgres/dao/OrderRepository.kt
  market/market-ports/market-persister-postgres/src/main/kotlin/co/nilin/opex/market/ports/postgres/dao/TradeRepository.kt
  market/market-ports/market-persister-postgres/src/main/kotlin/co/nilin/opex/market/ports/postgres/impl/UserQueryHandlerImpl.kt
  market/market-ports/market-persister-postgres/src/test/kotlin/co/nilin/opex/market/ports/postgres/impl/UserQueryHandlerTest.kt
  user-management/keycloak-gateway/src/main/kotlin/co/nilin/opex/auth/gateway/data/ForgotPasswordRequest.kt
  user-management/keycloak-gateway/src/main/kotlin/co/nilin/opex/auth/gateway/extension/UserManagementResource.kt
  user-management/keycloak-gateway/src/main/resources/application.yml
  utility/error-handler/src/main/kotlin/co/nilin/opex/utility/error/data/OpexError.kt
  wallet/wallet-app/src/main/kotlin/co/nilin/opex/wallet/app/controller/WithdrawController.kt
  wallet/wallet-core/src/main/kotlin/co/nilin/opex/wallet/core/service/WithdrawService.kt
  wallet/wallet-ports/wallet-persister-postgres/src/main/resources/schema.sql
Labels: bug, enhancement

#320 Close #319: wallet creation bug
  preferences-dev.yml
  wallet/wallet-app/src/main/kotlin/co/nilin/opex/wallet/app/service/UserRegistrationService.kt
Labels: bug
