Repository opexdev/core, pull requests merged in 2022-05, with the labels that each got.

#255 Close #253, Add IRT, BSC and BUSD currency
  accountant/accountant-ports/accountant-persister-postgres/src/main/resources/data.sql
  api/api-ports/api-persister-postgres/src/main/resources/data.sql
  bc-gateway/bc-gateway-ports/bc-gateway-persister-postgres/src/main/resources/data.sql
  docker-compose.yml
  matching-engine/matching-engine-app/src/main/resources/application.yml
  wallet/wallet-ports/wallet-persister-postgres/src/main/resources/data.sql
Labels: enhancement, prio@high

#261 258 fix vault resetting secrets issue
  docker-compose.yml
  docker-images/vault/vault.json
  docker-images/vault/workflow-vault.sh
Labels: bug, prio@high

#260 Fix wrong keycloak session ip
  README.md
Labels: bug, prio@high

#262 Close #257, Add service health checks
  accountant/accountant-app/Dockerfile
  accountant/accountant-app/pom.xml
  accountant/accountant-ports/accountant-wallet-proxy/pom.xml
  admin/admin-app/Dockerfile
  api/api-app/Dockerfile
  bc-gateway/bc-gateway-app/Dockerfile
  captcha/captcha-app/Dockerfile
  docker-compose.yml
  docker-images/postgres/Dockerfile
  docker-images/vault/Dockerfile
  docker-images/vault/workflow-vault.sh
  eventlog/eventlog-app/Dockerfile
  eventlog/eventlog-app/pom.xml
  matching-engine/matching-engine-app/Dockerfile
  matching-engine/matching-engine-app/pom.xml
  matching-gateway/matching-gateway-app/Dockerfile
  referral/referral-app/Dockerfile
  storage/storage-app/Dockerfile
  user-management/keycloak-gateway/Dockerfile
  wallet/wallet-app/Dockerfile
  websocket/websocket-app/Dockerfile
Labels: enhancement

#277 Release v1.0.0-beta.2
  bc-gateway/bc-gateway-core/src/main/kotlin/co/nilin/opex/bcgateway/core/service/WalletSyncServiceImpl.kt
  bc-gateway/bc-gateway-ports/bc-gateway-persister-postgres/src/main/kotlin/co/nilin/opex/bcgateway/ports/postgres/impl/AssignedAddressHandlerImpl.kt
  bc-gateway/bc-gateway-ports/bc-gateway-persister-postgres/src/main/kotlin/co/nilin/opex/bcgateway/ports/postgres/impl/CurrencyHandlerImpl.kt
  bc-gateway/bc-gateway-ports/bc-gateway-wallet-proxy/src/main/kotlin/co/nilin/opex/bcgateway/ports/walletproxy/impl/WalletProxyImpl.kt
  matching-gateway/matching-gateway-port/matching-gateway-submitter-kafka/src/main/kotlin/co/nilin/opex/matching/gateway/ports/kafka/submitter/service/KafkaHealthIndicator.kt
  preferences-demo.yml
  preferences-dev.yml
  referral/referral-ports/referral-eventlistener-kafka/src/main/kotlin/co/nilin/opex/referral/ports/kafka/listener/config/KafkaConfig.kt
  wallet/wallet-ports/wallet-persister-postgres/src/main/kotlin/co/nilin/opex/wallet/ports/postgres/dao/TransactionRepository.kt
  wallet/wallet-ports/wallet-persister-postgres/src/main/kotlin/co/nilin/opex/wallet/ports/postgres/model/CurrencyRateModel.kt
Labels: bug, enhancement

#279 Close #266, Write tests for create and cancel order
  accountant/accountant-core/pom.xml
  api/api-ports/api-persister-postgres/pom.xml
  api/api-ports/api-persister-postgres/src/test/kotlin/co/nilin/opex/api/ports/postgres/impl/MarketQueryHandlerTest.kt
  api/api-ports/api-persister-postgres/src/test/kotlin/co/nilin/opex/api/ports/postgres/impl/OrderPersisterTest.kt
  api/api-ports/api-persister-postgres/src/test/kotlin/co/nilin/opex/api/ports/postgres/impl/SymbolMapperTest.kt
  api/api-ports/api-persister-postgres/src/test/kotlin/co/nilin/opex/api/ports/postgres/impl/TradePersisterTest.kt
  api/api-ports/api-persister-postgres/src/test/kotlin/co/nilin/opex/api/ports/postgres/impl/UserQueryHandlerTest.kt
  api/api-ports/api-persister-postgres/src/test/kotlin/co/nilin/opex/api/ports/postgres/impl/sample/Samples.kt
  bc-gateway/bc-gateway-core/pom.xml
  matching-gateway/matching-gateway-app/pom.xml
  matching-gateway/matching-gateway-app/src/main/kotlin/co/nilin/opex/matching/gateway/app/service/OrderService.kt
  matching-gateway/matching-gateway-app/src/test/kotlin/co/nilin/opex/matching/gateway/app/service/OrderServiceTest.kt
  matching-gateway/matching-gateway-port/matching-gateway-submitter-kafka/src/main/kotlin/co/nilin/opex/matching/gateway/ports/kafka/submitter/service/KafkaHealthIndicator.kt
  pom.xml
  wallet/wallet-core/pom.xml
  wallet/wallet-core/src/test/kotlin/co/nilin/opex/wallet/core/service/TransferServiceTest.kt
  wallet/wallet-ports/wallet-persister-postgres/pom.xml
  wallet/wallet-ports/wallet-persister-postgres/src/test/kotlin/co/nilin/opex/wallet/ports/postgres/impl/CurrencyServiceTest.kt
  wallet/wallet-ports/wallet-persister-postgres/src/test/kotlin/co/nilin/opex/wallet/ports/postgres/impl/WalletManagerTest.kt
  wallet/wallet-ports/wallet-persister-postgres/src/test/kotlin/co/nilin/opex/wallet/ports/postgres/impl/WalletOwnerManagerTest.kt
Labels: enhancement

#283 #254: Custom verification service
  docker-compose.yml
  user-management/keycloak-gateway/src/main/kotlin/co/nilin/opex/auth/gateway/data/RegisterUserRequest.kt
  user-management/keycloak-gateway/src/main/kotlin/co/nilin/opex/auth/gateway/extension/UserManagementResource.kt
  user-management/keycloak-gateway/src/main/kotlin/co/nilin/opex/auth/gateway/model/ActionTokenResult.kt
  user-management/keycloak-gateway/src/main/kotlin/co/nilin/opex/auth/gateway/utils/ActionTokenHelper.kt
  user-management/keycloak-gateway/src/main/resources/application.yml
  user-management/keycloak-gateway/src/main/resources/opex-realm.json
  utility/error-handler/src/main/kotlin/co/nilin/opex/utility/error/data/OpexError.kt
Labels: enhancement
